agent:
  alpha: 0.00025
  beta: 0.00025
  tau: 1e-3
  gamma: 0.99 
  max_size: 1_000_000
  batch_size: 128
  save_path: 'runs/test_5'
  max_steps: 5_000_000 # Environment steps
  actor_buffer_size: 1000
  update_params_interval: 50 #  Learning steps
  checkpoints_interval: 1000 # Learning steps.
env:
  name:   'LunarLanderContinuous-v2' #'MountainCarContinuous-v0' #'PhenoEnvContinuous-v0'
memory:
  save_checkpoints: False
  warm_start: False
  n_random_actions: 0
  prioritized: False
  alpha: 0.7
  beta: 0.5
  random_state: 

