#!/bin/bash

#SBATCH -p gtx1080
#SBATCH --gres=gpu:1
#SBATCH --job-name=Agent
#SBATCH --ntasks-per-node=8
#SBATCH --time=6:00:00

source /home/mjad1g20/.bashrc
#module load conda/py3-latest
source activate rrlib 

#conda env list
python --version
which python
#python BLSSM.py
python test_d3pg.py
#python BLSSM_mg5.py
