agent:
  max_exploration_eps: 0.5 
  final_exploration: 0.1 
  final_exploration_frame: 10_000
  alpha: 0.0025
  beta: 0.00025
  tau: 1. 
  gamma: 0.99 
  max_size: 1_000_000
  batch_size: 128 
  save_path: 'tests/apex_dqn_8'
  double_dqn: True
  multi_step_n: 3
  q_update_freq: 100
  send_experience_freq: 100
  learning_starts: 5000
  num_workers: 6

  timesteps_per_iteration: 10000
  max_samples: 2_000_000

env:
  name: 'CartPole-v1'
memory:
  warm_start: False
  n_random_actions: 0
  prioritized: False
  alpha: 0.7
  beta: 0.5
  random_state: 

