agent:
  max_exploration_eps: 0.5 
  final_exploration: 0.1 
  final_exploration_frame: 10_000
  alpha: 0.0001
  beta: 0.001
  tau: 0.001 
  gamma: 0.99 
  max_size: 1_000_000
  batch_size: 64
  save_path: 'tests/apex_ddpg_6'
  double_dqn: True
  multi_step_n: 3
  q_update_freq: 100
  send_experience_freq: 100
  learning_starts: 5000
  num_workers: 37
  noise_type: "gauss"

  timesteps_per_iteration: 10000
  max_samples: 5_000_000

env:
  name: 'LunarLanderContinuous-v2'
memory:
  warm_start: False
  n_random_actions: 0
  prioritized: False
  alpha: 0.7
  beta: 0.5
  random_state: 

