agent:
  initial_exploration: 1. 
  final_exploration: 0.1 
  final_exploration_frame: 10_000
  alpha: 0.001
  beta: 0.00025
  tau: 1. 
  gamma: 0.99 
  max_size: 2000
  batch_size: 32
  save_path: 'tests/double_dqn'
  double_dqn: True
env:
  name: 'CartPole-v1'
memory:
  warm_start: False
  n_random_actions: 0
  prioritized: False
  alpha: 0.7
  beta: 0.5
  random_state: 

